# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty
# relative_permalinks: true

# Setup
title: Embracing my inner nerd!
tagline: "Phillip Emmons"
description: 'Personal adventures, technical write-ups, hobbies, and a place to exchange thoughts.'
url: http://philemmons.github.io
baseurl: "/content"
paginate: 3
sourceUrl: https://github.com/poole/lanyon

disqus_baseurl: "https://philemmons.github.io/content/"
disqus_shortname: github.io

ga_tracking_id: "G-R2SNFZQ2YG"

email: pemmons
linkedInUrl: phillip-t-emmons/
githubUrl: https://github.com/philemmons/
# fbUrl : phillip.t.emmons/
# pinterestUrl: philemmons
# skypeUrl: #
# snapchatID: zathor9902
# instagramUrl: emmons9902/


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# About/contact
author:
  name: Phillip Emmons
  contact: philemmons.now@gmail.com

# Custom vars
version:             2.0.1
